"""Stable core contracts for planner implementations."""

from __future__ import annotations

from pathplanning.data_structures.tree_array import ArrayTree, Tree
from pathplanning.nn.index import (
    KDTreeIndex,
    KDTreeNnIndex,
    NaiveIndex,
    NaiveNnIndex,
    NearestNeighborIndex,
)

from .contracts import (
    ContinuousProblem,
    ContinuousSpace,
    ContinuousSpaceMetadata,
    DiscreteGraph,
    DiscreteProblem,
    DistanceAwareGoalRegion,
    ExactGoalTest,
    GoalRegion,
    GoalState,
    GoalTest,
    HeuristicDiscreteGraph,
    InterpolatingContinuousSpace,
    ManipulabilitySpace,
    MultiAgentProblem,
    Objective,
    RiemannianMetricSpace,
    State,
    SupportsBatchCollisionStepMotionCheck,
    SupportsBatchMotionCheck,
    SupportsCollisionStepMotionCheck,
    TemporalProblem,
    TimeInterval,
    ValidatingDiscreteGraph,
)
from .params import JitParams, RitParams, RoadmapParams, RrtParams
from .results import MultiAgentPlanResult, PlanResult, StopReason, TemporalPlanResult
from .trace import PlannerTrace, TraceOptions
from .types import RNG, BoolArray, Float, FloatArray, Mat, N, NodeId, S, Vec

__all__ = [
    "DiscreteGraph",
    "HeuristicDiscreteGraph",
    "ValidatingDiscreteGraph",
    "GoalTest",
    "ExactGoalTest",
    "DiscreteProblem",
    "TemporalProblem",
    "MultiAgentProblem",
    "TimeInterval",
    "ContinuousSpace",
    "InterpolatingContinuousSpace",
    "ManipulabilitySpace",
    "ContinuousSpaceMetadata",
    "GoalRegion",
    "DistanceAwareGoalRegion",
    "GoalState",
    "SupportsBatchMotionCheck",
    "SupportsCollisionStepMotionCheck",
    "SupportsBatchCollisionStepMotionCheck",
    "Objective",
    "RiemannianMetricSpace",
    "ContinuousProblem",
    "PlanResult",
    "TemporalPlanResult",
    "MultiAgentPlanResult",
    "StopReason",
    "PlannerTrace",
    "TraceOptions",
    "RrtParams",
    "RoadmapParams",
    "RitParams",
    "JitParams",
    "State",
    "NearestNeighborIndex",
    "NaiveNnIndex",
    "KDTreeNnIndex",
    "NaiveIndex",
    "KDTreeIndex",
    "ArrayTree",
    "Tree",
    "NodeId",
    "Float",
    "FloatArray",
    "BoolArray",
    "S",
    "N",
    "RNG",
    "Vec",
    "Mat",
]
